apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc

spec:
  accessModes:
    - {{ .Values.redis.persistence.accessMode }}
  
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
  
  storageClassName: {{ .Values.redis.persistence.storageClass }}