apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis

spec:
  replicas: {{ .Values.redis.replicaCount }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis

          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"

          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}

          command:
            - redis-server
            - --requirepass
            - {{ .Values.redis.password | quote }}

          ports:
            - containerPort: 6379

          volumeMounts:
            - name: redis-data
              mountPath: /data

      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc