apiVersion: v1
kind: Service
metadata:
  name: python-api

spec:
  selector:
    app: python-api
  
  type: {{ .Values.pythonApi.service.type }}

  ports:
    - port: {{ .Values.pythonApi.service.port }}
      targetPort: {{ .Values.pythonApi.service.targetPort }}